import type { Metadata } from "next";
import { Anton, Open_Sans, Archivo_Black } from "next/font/google";
import "./globals.css";

const inter = Open_Sans({ subsets: ["latin"] });

const anton = Archivo_Black({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-anton",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${anton.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
