

import type { Metadata } from "next";
import { Open_Sans, Archivo_Black, Outfit } from "next/font/google";

import "./globals.css";
import Footer from "./shared/Footer";
import Navbar from "./components/Navbar";

const openSans = Open_Sans({
  subsets: ["latin"],
});

const anton = Archivo_Black({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-anton",
  weight: "400",
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${anton.variable} ${outfit.variable}`}
    >
 
 <body className={`${openSans.className} min-h-screen flex flex-col`}>

   
      <Navbar/>
<main className="flex-1">
{children}
</main>
      <Footer/>
      </body>

    </html>
  );
}